DROP TABLE IF EXISTS order_and_saleunit;
DROP TABLE IF EXISTS basket;
DROP TABLE IF EXISTS saleunits;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS categories;